version: '3.7'
services:
  database:
    image: postgres:11.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: hephaestus
      POSTGRES_USER: hephaestus
      POSTGRES_PASSWORD: admin
